language: python
python:
  - "2.7"


sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - TARGETS="aarch64 armv5e  mips64 core2-64 i586"
        - YP_RELEASE=2.1
        - CROPS_RELEASE=latest
        - CODI_ADDR=localhost
        - CODI_PORT=10000
        - secure: "YrpUzQT/3LnEqOeoRSf+iV6FmlrYAwCJYxZgdhCaxGOFWKtmfNDAM8K9L/I/9NS3d1MD28YQ6o0gTggvjKCensMHu69B2ln++qKHqNG1ZWfSTU+jvhyI7BRdORh2qIx7laVUn48kXSazhQIDEgwcj0Qvwmhwwosjsy6Q74qCzO4hHqFUIWL97vdfzqJss/rKb3+Yp06rFf8T6nepKhUJGksOXDsVsZs00sxKQmMH/7Ryu5ylacHTnp27wPkb5k0CsvMUNFG7bNRy3QjTl4mi3RXXTzgreN8Z+ES4HLeHfKCS2J+uUzg4Rj0zUqyLtmiGsOBK6chO3/KYMU+nsOILHVvHm+Hyp1GNT+PVgDhtBHvgCfNC+JONp2fKGHMQ9ZPKwPVleoS2U8lmh65WQ6dkN42h0ac9Q9clSQtLezWLbvbypo3g+VMPYK49RWAzQfHD3RUC81tcApoQ5Zy5cXJa0m7bvnZmSbfiv+ETkPkR6y0MPwr60tCcDb3wNV6CDffQ/Scnv8VCfKDE/wxjfllPWXCY93FTurMskus8AIPa5Wcx8hPV5ve4VIVmgfjqbY+C6x4Qv5PCPufijF13HqYG8UF7+ybrOqamgau9LfHnGtSqyM8bf1A+nZZtZ2bE5Mq2fsUIWKNFPp9Dp379Q/79CcwVdFFzpvpgPAWPjoz9Few="
        - secure: "Ckr57YwuNEKBuVI4atxwtH9c3p+YQENpV98SricIqfHgXFNhEyM9Zb/JwfZphef71eiXihlCjXZ9YBHBGhpl8T0t4HOFM2JMZ26VhOZBypIqfhSIhl3kNJfRONK3ZRrmoEuaj7L7Y0j1WOkadeES4kH6Q8f0c6IwL/6X1VHMvRT2mmz4e2oeuqZQ3RRqNBi4dv+IHqUwyUIuF0OFQezuxoSbZEJAHgB+KHPuiWc+GBu1cp71wd/VSqMr5smXzk14yAoVFJivXfFgJmQqxLd78ojhMBs0674wEgTyPQzt5AWMQ7sPBSfqop93+pdFq675qpY3EktEa89j0aMZ/N0iXRndLCm7vwTu1jpQ8iqtqo6n5HZvPIdTX6YKQilw954mvJCrSYHIzteIrTTXDk+eKqKeyxFFREP/WcxC2et6tt89KpA8QTRkzFerj3Ee7nVSugaXdv6lptHbcpRLV3pPhJMvubTnCNQuoj3zpxqcpyqv98FNQJ7Sw/CVEa81xzPJ0SREerpE8Yx2qCPQ/zivrouZfWZJ3jjC8Z4z7iagSWrqJY+E2sJORyrMbNW/RuDzTGSqnINzgulxqcDQzkprbXers8GlFAx84MxdOh0B7wIDmAb21j9ar6uuxWhLUYRvUrdwHWpoNXhyzY2Tx2iLerlPiqDKS5m2o0VNvQKWDoM="
        - secure: "n5wDUIBw6bp0uSQJ0/T9l/sfqQy9RkEeShaoGVtS1beujyQedhGE1nQo6Kc9FPI76VluYivV7arI/wqmiJ3rfTPRMy0PrzjljcX4NuHjKxYZ7dzaRNPLltWI3xYvUAmML8wFEkZjgVVzdoCSkCkAtT53R2X7PD/7RhHHc/UofiUGc/6Ee0EMgtaSZ+TSNcWqoRF1JeXK+5POG4qTDr2ojSlekI9z1ljK4QDa3utdCAzfmoYKc/Q0eFFmiI7U9jbW0fawgvJVWe9Krs66+Vb1/LS+/dqi8jk+HanMF0P3ACF2DQ93Wzpdlk3INA8M654bxTWKFdsXtPPJ9pFSkdBEOSIftHsJu5+v6YbGQMtIr1yBdjgZOBOo4TyUsukFaVnlhjsJSI1jOmPpRw+W06efcV/f1yp4Puwal0rS2kRo5W8oMRVguRZ+3i5YJdEUjZQRLcXzgeorGq8366qJ9M+at00jS3JDxeD57+sP0oc34f3ezlFi9rDPubg+3sRbWgdTfR2jCXZYCwE6djecrvvbpBatVB1abCSJ46uXjrSi67NNUAZ14H5IEOKemo5tVaniGTr1Vg7C6rSw0hXW7QFo4vSwKxf6rSaRoXoeFj8CI+Af7STLYSjYfG/tgze4bNeXau11cOYo2E1kyhrdok6DnH4iJkAP2a28FXHjQLwF+lE="


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  - docker pull crops/codi:latest

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
install:
  - pip install requests

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/base/tests/unit/

script:
  - docker version
  - git submodule update --init --recursive
  - echo "set Docker Repo"
  - source ./base/scripts/setDockerhubRepo.sh
  - echo "Building SDK Containers"
  - ./scripts/build_containers.sdk
  - docker images
  - python tests.py


after_success:
  - ./base/scripts/pushToDockerhub.sh




notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
