language: python
python:
  - "2.7"


sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - TARGETSREAL="aarch64 armv5e  mips64 core2-64 i586"
        - TARGETS="i586"
        - YP_RELEASE=2.1
        - CROPS_RELEASE=latest
        - CODI_ADDR=localhost
        - CODI_PORT=10000
        - secure: "nxP4M0TiPkUwtlgEGhutaK/EXZJPIOXmw0R9BQsVPogQR7rTe060J1RqZX3t5KFqrwsyEOdIU5z2cFDe/CcvcCzdx9/AU5HcvCnCBNlFHWHlc18B92gTOohM7Ewx0IQtl2KbHLqeP5ejpcHPvTG+Su26h4yZcMqdIdKR9/PGWBgE/67TWqNmOTTeDv5lOSJj5kUt4bOTmKWUGMFW/8SbOnDPDF9iTzPWCWIhoq3ET5KaUw/jlF4xEJA3CVNqiBaY8CKhH+zmFw/oANqN/z61Jl1+goBoV3MQ0DP9LENMp5uASENACbAsOAflbgdL6WiURkcRcret/sHsWMo2fo7D8mqHBii6oXbPu1o/D7rIId3FneOoX+o1xdCFWQaQn9k3WULc9yYGT/xu+gfCIUvAAteXMSAVYIA3PXpZojrcnLNhkYr8T5+VNe2szJd8fs2/DPXbHESslaTRWLWdw2tyYvwtS9kwT4QzHPerRHwOScWEJ3kbyn+Y/zjEeswsuIOvaisKf2GtwRO1PO80dx0J5tNUd4hfKTppW4N/lcjMboIQJObg8aHjKxkzzWRTJkf7evLPIpAJXrjoQIdwu7SpXhahCuR99c7lP50SIyjHRcwsB1T5RgzcrI4+/FO1+4IfbaI059TatQSxrUkm9o8VI1gqAUz8yjPZmGusmUjjZl4=" # DOCKER_EMAIL_crops
        - secure: "UgwqADtuLrX8AxzP1aHBmk8DkC8m9h49KsKlduaC8pJZtt7Ftmv+/d6dz+SgK5qZFLdnkujv46jMdafRfAujRIApse3x8ADUHdAb0HEapwS7phBYAS37/3dg4KEdFlAt45EhaY6bLU3SSS27SVnrhly5egMH3BnGR4eOQXtd1XjQeXycncV6MjlXYGIjRNkFRjQu4De+biRmBDilpVFnW1XaKszagxteBOFcRwU9GSfSyWNLb3GNnTB76AKTGbpvbhZ5JB5z0Py3xrnxxLAxnFg3+e4An4tRbU4jMvLvzrZg4UpqHIFEl33s5P6zQuNRVmsp3yXxsAlMc/3XeDr8RzmFbrxFO7EwwztPv4aQ1Uqn79HPJSRhrIz+U5T/QqnfLELMCxXXA6jM9JT31ThGK9iGEJ9BK/eMzRCGrLtmpGxbaiBrdU48RAmgcupRS3WRxbFrslnKUjnDv3MHNtBIqX8DsrFKQ6N584XhmcVjrUOtMJFKOZ3iS5+4UbiI4aE5cPrG5LDZ+04kQnrq+WEdOIYd4PzdWt+JC1HSfJLo2/0UDZAedGMo/OG2bBXFXVNNbt3UGXpmaE9DPLwLh2z97mQ+CSt8wQDuQUD8GuL8SJz77gpeOGHnFbOuVbhtgRuXMAZBCl1VESVVPRWKH6f9Hlt43kEg3QUJU3GKYo+ArAI=" # DOCKER_PASS_crops

compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  - docker pull crops/codi:latest

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
install:
  - pip install requests

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/base/tests/unit/

script:
  - docker version
  - git submodule update --init --recursive
  - echo "set Docker Repo"
  - source ./base/scripts/setDockerhubRepo.sh
  - echo "Building SDK Containers"
  - ./scripts/build_containers.sdk
  - docker images
  - python tests.py
  - ./scripts/pushToDockerhub.sh

after_success:
  - echo "after sucess placeholder"




notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
