language: python
python:
  - "2.7"


sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - TARGETSREAL="aarch64 armv5e  mips64 core2-64 i586"
        - TARGETS="i586"
        - YP_RELEASE=2.1
        - CROPS_RELEASE=latest
        - CODI_ADDR=localhost
        - CODI_PORT=10000
        - secure: chN7ohOONiBc6Tv8sd/qDZMzC0NuOnAOMz8jwRLk6YR4cskEuBggzN0GuvJHJTqBWDHUyWOno4v09L4yGzyOI8tqyu9ZbdIYLbwGefDV5DcJ9qy7jof6o30KtPoss5S0lHdziMS6B5w0VrzhfO43MqdvkBY5PLm/B05rC9TKuEuH7yBEHYJmf8cJFa/Ef3w5m6CyqVwa931rTLbL10XdW38VybEQ6z/98ZUqnCHsel937m/WayxE+Hek9anIcDKFnoXiX6RrFvQfdhzHRZQi1AgIK7IEPfVeugpj89+q9dm+yw/Bbm5BeMw1nPTlMLwbanNQp3uu1djJbj7eqg+GaXkchzDjfB/+O4qjrH1TTKRwMvZ6V8NOjC1aFm29QCH4c4yIJhaVDke5963fPpEASj9ZZ3L2j+ZhHW9RRauc9hBJXZfaN9gbiYGonaRRR1bEaPnap+b9vrTgiMMLXc3XS7tsVVtriAhRnao2zRAcNdns/fDh52y4peDL+pXOt5AjuN3Zef35i+/l1HnSMhvWEcHG7QIvy3EjJ1klND3Vyqz4nRVd7mJdTXI/lsp34pfsDzGM3xWYOq6PhQ9FzCTR6XkNVt+Jyhq+qfd/DRXi0TZmZQA6xCfYEVZnA0VFld4CF+YhiPCHFUk0KwRAI1aUyrEqCphKcVgjNRWT94p2bPM=   # DOCKER_EMAIL_bavery
        - secure: POMpze/nSxTxbMsKvOvXIVhppO01NXwFI95dZLEvlND0afP+rmohBCzFhKjhA6Irpxqf36vQ/2Qn/mCMU5XsMrer+KUmPsu+DOlD+iYesU6WNrnx/rydgTQ1KZxLRIZvGEoKSUd7NuX0XT3EXsfbuGEIIRceb/6i7EsDzyvNB5LbyhtRfe9bvP8590+R0w5hgDUuD7iwMmZpPATpQInDLf4trOfxDeB9j4RkWDCqlW40Pwjj0Nf/3EaL8HWMEevvwc6KrltuimP21OJCXEuwlCM8rZnNHBKgFw260QfwP2syJylqy8YXXI3luoXJazwE8HZrHQ+ue3LBULWQM3efamVffMLzAMpz30AYxHHprmYkn6FHsP5rqU6MzSc039q+CHFoAB9uEd3WqwR7beiwzL71H70k2xKU9IdM8DtzF+AP7/51J2d5Ev49Cz+EPJu843g5sJjiSd+ebsqC/MlRRmgstE+fzGMyaAoP2E2PjMS5El9W7ffPWow4lwR1HVe7V2IQWym2YECEhIgEfZmUzUxDTB2PeXucrja6EPtZhcLI13YMT5AgvT472Y5mpUBz85S9+WYjxuMs0Ick3d+QzzHpvjQ5Ebb9SDHGl4rlxOxkQJ6zVpwePeBKlYoJne8CbYfmFQmaUA2LG32RqcNuySkXcJM/YC2uVF/bxYVXgms= # DOCKER_PASS_bavery


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  - docker pull crops/codi:latest

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
install:
  - pip install requests

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/base/tests/unit/

script:
  - docker version
  - git submodule update --init --recursive
  - echo "set Docker Repo"
  - source ./base/scripts/setDockerhubRepo.sh
  - echo "Building SDK Containers"
  - ./scripts/build_containers.sdk
  - docker images
  - nmap localhost | egrep 10000
  - python tests.py
  - nmap localhost | egrep 10000
  - ./base/scripts/pushToDockerhub.sh

after_success:
  - echo "after_success placeholder"




notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
