language: python
python:
  - "2.7"


sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - TARGETSREAL="aarch64 armv5e  mips64 core2-64 i586"
        - TARGETS="i586"
        - YP_RELEASE=2.1
        - CROPS_RELEASE=latest
        - CODI_ADDR=localhost
        - CODI_PORT=10000
        - secure: chN7ohOONiBc6Tv8sd/qDZMzC0NuOnAOMz8jwRLk6YR4cskEuBggzN0GuvJHJTqBWDHUyWOno4v09L4yGzyOI8tqyu9ZbdIYLbwGefDV5DcJ9qy7jof6o30KtPoss5S0lHdziMS6B5w0VrzhfO43MqdvkBY5PLm/B05rC9TKuEuH7yBEHYJmf8cJFa/Ef3w5m6CyqVwa931rTLbL10XdW38VybEQ6z/98ZUqnCHsel937m/WayxE+Hek9anIcDKFnoXiX6RrFvQfdhzHRZQi1AgIK7IEPfVeugpj89+q9dm+yw/Bbm5BeMw1nPTlMLwbanNQp3uu1djJbj7eqg+GaXkchzDjfB/+O4qjrH1TTKRwMvZ6V8NOjC1aFm29QCH4c4yIJhaVDke5963fPpEASj9ZZ3L2j+ZhHW9RRauc9hBJXZfaN9gbiYGonaRRR1bEaPnap+b9vrTgiMMLXc3XS7tsVVtriAhRnao2zRAcNdns/fDh52y4peDL+pXOt5AjuN3Zef35i+/l1HnSMhvWEcHG7QIvy3EjJ1klND3Vyqz4nRVd7mJdTXI/lsp34pfsDzGM3xWYOq6PhQ9FzCTR6XkNVt+Jyhq+qfd/DRXi0TZmZQA6xCfYEVZnA0VFld4CF+YhiPCHFUk0KwRAI1aUyrEqCphKcVgjNRWT94p2bPM=   # DOCKER_EMAIL_bavery
        - secure: POMpze/nSxTxbMsKvOvXIVhppO01NXwFI95dZLEvlND0afP+rmohBCzFhKjhA6Irpxqf36vQ/2Qn/mCMU5XsMrer+KUmPsu+DOlD+iYesU6WNrnx/rydgTQ1KZxLRIZvGEoKSUd7NuX0XT3EXsfbuGEIIRceb/6i7EsDzyvNB5LbyhtRfe9bvP8590+R0w5hgDUuD7iwMmZpPATpQInDLf4trOfxDeB9j4RkWDCqlW40Pwjj0Nf/3EaL8HWMEevvwc6KrltuimP21OJCXEuwlCM8rZnNHBKgFw260QfwP2syJylqy8YXXI3luoXJazwE8HZrHQ+ue3LBULWQM3efamVffMLzAMpz30AYxHHprmYkn6FHsP5rqU6MzSc039q+CHFoAB9uEd3WqwR7beiwzL71H70k2xKU9IdM8DtzF+AP7/51J2d5Ev49Cz+EPJu843g5sJjiSd+ebsqC/MlRRmgstE+fzGMyaAoP2E2PjMS5El9W7ffPWow4lwR1HVe7V2IQWym2YECEhIgEfZmUzUxDTB2PeXucrja6EPtZhcLI13YMT5AgvT472Y5mpUBz85S9+WYjxuMs0Ick3d+QzzHpvjQ5Ebb9SDHGl4rlxOxkQJ6zVpwePeBKlYoJne8CbYfmFQmaUA2LG32RqcNuySkXcJM/YC2uVF/bxYVXgms= # DOCKER_PASS_bavery
        - secure: nxP4M0TiPkUwtlgEGhutaK/EXZJPIOXmw0R9BQsVPogQR7rTe060J1RqZX3t5KFqrwsyEOdIU5z2cFDe/CcvcCzdx9/AU5HcvCnCBNlFHWHlc18B92gTOohM7Ewx0IQtl2KbHLqeP5ejpcHPvTG+Su26h4yZcMqdIdKR9/PGWBgE/67TWqNmOTTeDv5lOSJj5kUt4bOTmKWUGMFW/8SbOnDPDF9iTzPWCWIhoq3ET5KaUw/jlF4xEJA3CVNqiBaY8CKhH+zmFw/oANqN/z61Jl1+goBoV3MQ0DP9LENMp5uASENACbAsOAflbgdL6WiURkcRcret/sHsWMo2fo7D8mqHBii6oXbPu1o/D7rIId3FneOoX+o1xdCFWQaQn9k3WULc9yYGT/xu+gfCIUvAAteXMSAVYIA3PXpZojrcnLNhkYr8T5+VNe2szJd8fs2/DPXbHESslaTRWLWdw2tyYvwtS9kwT4QzHPerRHwOScWEJ3kbyn+Y/zjEeswsuIOvaisKf2GtwRO1PO80dx0J5tNUd4hfKTppW4N/lcjMboIQJObg8aHjKxkzzWRTJkf7evLPIpAJXrjoQIdwu7SpXhahCuR99c7lP50SIyjHRcwsB1T5RgzcrI4+/FO1+4IfbaI059TatQSxrUkm9o8VI1gqAUz8yjPZmGusmUjjZl4= # DOCKER_EMAIL_crops
        - secure: UgwqADtuLrX8AxzP1aHBmk8DkC8m9h49KsKlduaC8pJZtt7Ftmv+/d6dz+SgK5qZFLdnkujv46jMdafRfAujRIApse3x8ADUHdAb0HEapwS7phBYAS37/3dg4KEdFlAt45EhaY6bLU3SSS27SVnrhly5egMH3BnGR4eOQXtd1XjQeXycncV6MjlXYGIjRNkFRjQu4De+biRmBDilpVFnW1XaKszagxteBOFcRwU9GSfSyWNLb3GNnTB76AKTGbpvbhZ5JB5z0Py3xrnxxLAxnFg3+e4An4tRbU4jMvLvzrZg4UpqHIFEl33s5P6zQuNRVmsp3yXxsAlMc/3XeDr8RzmFbrxFO7EwwztPv4aQ1Uqn79HPJSRhrIz+U5T/QqnfLELMCxXXA6jM9JT31ThGK9iGEJ9BK/eMzRCGrLtmpGxbaiBrdU48RAmgcupRS3WRxbFrslnKUjnDv3MHNtBIqX8DsrFKQ6N584XhmcVjrUOtMJFKOZ3iS5+4UbiI4aE5cPrG5LDZ+04kQnrq+WEdOIYd4PzdWt+JC1HSfJLo2/0UDZAedGMo/OG2bBXFXVNNbt3UGXpmaE9DPLwLh2z97mQ+CSt8wQDuQUD8GuL8SJz77gpeOGHnFbOuVbhtgRuXMAZBCl1VESVVPRWKH6f9Hlt43kEg3QUJU3GKYo+ArAI= # DOCKER_PASS_crops

compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION} net-tools nmap wget
  - docker pull crops/codi:latest

install:
  - pip install requests

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/base/tests/unit/

script:
  - docker version
  - git submodule update --init --recursive
  - echo "set Docker Repo"
  - source ./base/scripts/setDockerhubRepo.sh
  - echo "Building SDK Containers"
  - ./scripts/build_containers.sdk
  - ./scripts/startContainers.sh
  - docker ps
  - docker images
  - python tests.py
  - docker rmi -f crops/toolchain-base  crops/codi
  - ./base/scripts/pushToDockerhub.sh

after_success:
  - echo "after_success placeholder"




notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
